export const PortFolio = [
  {
    id: 1,
    imgUrl: "pro6.png",
    projectName: "Ghana.Gov Clone",
    code: "https://github.com/abdulwahabfuseini/Ghana.Gov",
    link: " https://ghana-gov-2a6e6.web.app",
    connect: "link.png",
    desc: "Ghana Government Office Website clone made with",
    tools: [
      { tool: "React.js" },
      { tool: "JavaScript" },
      { tool: "Firebase" },
      { tool: "Vite.js" },
      { tool: "TailwindCSS" },
    ],
  },
  {
    id: 2,
    imgUrl: "pro4.png",
    projectName: "Netflix Clone",
    code: "https://github.com/abdulwahabfuseini/Netflix-Clone",
    link: "https://netflix-clone-woad-nine.vercel.app/",
    connect: "link.png",
    desc: "Netflix Official Website clone made with",
    tools: [
      { tool: "Next.js" },
      { tool: "JavaScript" },
      { tool: "NextAuth" },
      { tool: "TailwindCSS" },
    ],
  },
  {
    id: 3,
    imgUrl: "quiz.png",
    projectName: "Quiz App",
    code: "https://github.com/abdulwahabfuseini/Quiz-App",
    link: "https://quiz-app-gray-rho-26.vercel.app/",
    connect: "link.png",
    desc: "An Online Quiz App made with",
    tools: [
      { tool: "Next.js" },
      { tool: "NextAuth" },
      { tool: "TypeScript" },
      { tool: "TailwindCSS" },
      { tool: "cloud.google" },
    ],
  },
  {
    id: 4,
    imgUrl: "read.png",
    projectName: "Readify",
    code: "https://github.com/abdulwahabfuseini/readify",
    link: "https://readify-orpin.vercel.app/",
    connect: "link.png",
    desc: "An Online Boook Search made with",
    tools: [
      { tool: "Next.js" },
      { tool: "NextAuth" },
      { tool: "TypeScript" },
      { tool: "TailwindCSS" },
      { tool: "cloud.google" },
      { tool: "Google Books Api" },
    ],
  },
  {
    id: 5,
    imgUrl: "pro7.png",
    projectName: "Revive Physiotherapy - Ghana",
    code: "https://github.com/abdulwahabfuseini/Revive-Physiotherapy-Ghana",
    link: "https://revive-physiotherapy-ghana.vercel.app/",
    connect: "link.png",
    desc: "A Physiotherapist Website made with",
    tools: [
      { tool: "Next.js" },
      { tool: "JavaScript" },
      { tool: "MongoDB" },
      { tool: "TailwindCSS" },
      { tool: "cloud.google" },
    ],
  },
  {
    id: 6,
    imgUrl: "pro1.png",
    projectName: "Rest ASSured Hotel",
    code: "https://github.com/abdulwahabfuseini/rest-aSSured",
    link: "https://rest-aSSured-3c437.web.app",
    connect: "link.png",
    desc: "A Hotel Booking Website made with",
    tools: [
      { tool: "React.js" },
      { tool: "JavaScript" },
      { tool: "Firebase" },
      { tool: "TailwindCSS" },
      { tool: "cloud.google" },
    ],
  },
  {
    id: 7,
    imgUrl: "store.png",
    projectName: "Groceries Store",
    code: "https://github.com/abdulwahabfuseini/Groceries-Store",
    link: "https://groceries-store-lovat.vercel.app/",
    connect: "link.png",
    desc: "An Online Groceries Store made with",
    tools: [
      { tool: "Next.js" },
      { tool: "NextAuth" },
      { tool: "TypeScript" },
      { tool: "React Redux" },
      { tool: "TailwindCSS" },
      { tool: "MongoDB" },
      { tool: "cloud.google" },
    ],
  },
  {
    id: 8,
    imgUrl: "pro2.png",
    projectName: "Mandem Store",
    code: "https://github.com/abdulwahabfuseini/Mandem-Store",
    link: "https://mandem-store-24ff1.web.app",
    connect: "link.png",
    desc: "An AcceSSories E-commerce Website made with",
    tools: [
      { tool: "React.js" },
      { tool: "React Redux" },
      { tool: "JavaScript" },
      { tool: "Firebase" },
      { tool: "TailwindCSS" },
    ],
  },
  {
    id: 9,
    imgUrl: "pro5.png",
    projectName: "Fast Food",
    code: "https://github.com/abdulwahabfuseini/fast-food",
    link: " https://react-auth-96023.web.app",
    connect: "link.png",
    desc: "Food Ordering and Delivery App made with",
    tools: [
      { tool: "React.js" },
      { tool: "React Redux" },
      { tool: "JavaScript" },
      { tool: "Firebase" },
      { tool: "TailwindCSS" },
    ],
  },
  // {
  //   id: 10,
  //   imgUrl: "pro5.png",
  //   projectName: "International Trade Properties",
  //   code: "https://github.com/abdulwahabfuseini/international-trade-properties",
  //   link: "international-trade-properties.vercel.app",
  //   connect: "link.png",
  //   desc: "E-commerce Website made with",
  //   tools: [
  //     { tool: "React.js" },
  //     { tool: "React Redux" },
  //     { tool: "JavaScript" },
  //     { tool: "Firebase" },
  //     { tool: "TailwindCSS" },
  //   ],
  // },
];


export const ProjectData = [
  {
    id: 1,
    imgUrl: "pro6.png",
    projectName: "Ghana.Gov Clone",
    link: " https://ghana-gov-2a6e6.web.app",

  },
  {
    id: 2,
    imgUrl: "pro4.png",
    projectName: "Netflix Clone",
    link: "https://netflix-clone-woad-nine.vercel.app/",
  },
  {
    id: 3,
    imgUrl: "pro7.png",
    projectName: "Revive Physiotherapy - Ghana",
    link: "https://revive-physiotherapy-ghana.vercel.app/",
  },
  {
    id: 4,
    imgUrl: "store.png",
    projectName: "Groceries Store",
    link: "https://groceries-store-lovat.vercel.app/",
  },
  {
    id: 5,
    imgUrl: "quiz.png",
    projectName: "Quiz App",
    link: "https://quiz-app-gray-rho-26.vercel.app/",
  },
]