export const PortFolio = [
  {
    id: 1,
    imgUrl: "pro6.png",
    projectName: "Ghana.Gov Clone",
    code: "https://github.com/abdulwahabfuseini/Ghana.Gov",
    link: " https://ghana-gov-2a6e6.web.app",
    connect: "link.png",
    desc: "Ghana Government Office Website clone made with",
    tools: [
      { tool: "React.js" },
      { tool: "JavaScript" },
      { tool: "Firebase" },
      { tool: "Vite.js" },
      { tool: "TailwindCss" },
    ],
  },
  {
    id: 2,
    imgUrl: "pro4.png",
    projectName: "Netflix Clone",
    code: "https://github.com/abdulwahabfuseini/Netflix-Clone",
    link: "https://netflix-clone-woad-nine.vercel.app/",
    connect: "link.png",
    desc: "Netflix clone made with",
    tools: [
      { tool: "Next.js" },
      { tool: "JavaScript" },
      { tool: "NextAuth" },
      { tool: "TailwindCss" },
    ],
  },
  {
    id: 3,
    imgUrl: "quiz.png",
    projectName: "Quiz App",
    code: "https://github.com/abdulwahabfuseini/Quiz-App",
    link: "https://quiz-app-gray-rho-26.vercel.app/",
    connect: "link.png",
    desc: "An Online Quiz App made with",
    tools: [
      { tool: "Next.js" },
      { tool: "NextAuth" },
      { tool: "TypeScript" },
      { tool: "TailwindCss" },
      { tool: "cloud.google" },
    ],
  },
  {
    id: 4,
    imgUrl: "pro7.png",
    projectName: "Revive Physiotherapy - Ghana",
    code: "https://github.com/abdulwahabfuseini/Revive-Physiotherapy-Ghana",
    link: "https://revive-physiotherapy-ghana.vercel.app/",
    connect: "link.png",
    desc: "A Physiotherapist Website made with",
    tools: [
      { tool: "Next.js" },
      { tool: "JavaScript" },
      { tool: "MongoDB" },
      { tool: "TailwindCss" },
      { tool: "cloud.google" },
    ],
  },
  {
    id: 5,
    imgUrl: "pro1.png",
    projectName: "Rest Assured Hotel",
    code: "https://github.com/abdulwahabfuseini/rest-assured",
    link: "https://rest-assured-3c437.web.app",
    connect: "link.png",
    desc: "A Hotel Booking Website made with",
    tools: [
      { tool: "React.js" },
      { tool: "JavaScript" },
      { tool: "Firebase" },
      { tool: "TailwindCss" },
      { tool: "cloud.google" },
    ],
  },
  {
    id: 6,
    imgUrl: "store.png",
    projectName: "Groceries Store",
    code: "https://github.com/abdulwahabfuseini/Groceries-Store",
    link: "https://groceries-store-lovat.vercel.app/",
    connect: "link.png",
    desc: "An Online Groceries Store made with",
    tools: [
      { tool: "Next.js" },
      { tool: "NextAuth" },
      { tool: "TypeScript" },
      { tool: "React Redux" },
      { tool: "TailwindCss" },
      { tool: "MongoDB" },
      { tool: "cloud.google" },
    ],
  },
  {
    id: 7,
    imgUrl: "pro2.png",
    projectName: "Mandem Store",
    code: "https://github.com/abdulwahabfuseini/Mandem-Store",
    link: "https://mandem-store-24ff1.web.app",
    connect: "link.png",
    desc: "An Accessories E-commerce Website made with",
    tools: [
      { tool: "React.js" },
      { tool: "React Redux" },
      { tool: "JavaScript" },
      { tool: "Firebase" },
      { tool: "TailwindCss" },
    ],
  },
  {
    id: 8,
    imgUrl: "pro5.png",
    projectName: "Fast Food",
    code: "https://github.com/abdulwahabfuseini/fast-food",
    link: " https://react-auth-96023.web.app",
    connect: "link.png",
    desc: "Food Ordering and Delivery App made with",
    tools: [
      { tool: "React.js" },
      { tool: "React Redux" },
      { tool: "JavaScript" },
      { tool: "Firebase" },
      { tool: "TailwindCss" },
    ],
  },
];


export const ProjectData = [
  {
    id: 1,
    imgUrl: "pro6.png",
    projectName: "Ghana.Gov Clone",
    link: " https://ghana-gov-2a6e6.web.app",

  },
  {
    id: 2,
    imgUrl: "pro4.png",
    projectName: "Netflix Clone",
    link: "https://netflix-clone-woad-nine.vercel.app/",
  },
  {
    id: 3,
    imgUrl: "pro7.png",
    projectName: "Revive Physiotherapy - Ghana",
    link: "https://revive-physiotherapy-ghana.vercel.app/",
  },
  {
    id: 4,
    imgUrl: "store.png",
    projectName: "Groceries Store",
    link: "https://groceries-store-lovat.vercel.app/",
  },
  {
    id: 5,
    imgUrl: "quiz.png",
    projectName: "Quiz App",
    link: "https://quiz-app-gray-rho-26.vercel.app/",
  },
]