import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import StarsCanvas from "@/components/Stars";
import Loading from "./loading";
import Navbar from "@/components/header/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, user-scalable=no" />
      </Head>
      <body className="relatidve w-full h-full text-white bg-black">
        <div className="z-20">
          <StarsCanvas />
        </div>
        <div className="z-50 relative">
          <Loading>
            <Navbar />
            <div className="mb-16 md:mb-72  lg:mb-28">{children}</div>
            <Footer />
          </Loading>
        </div>
      </body>
    </html>
  );
}
